### ISSUE TITLE
Copy filename: You must have a workspace opened.

### ISSUE THREAD

**Issue by Sco768** [Jack89ita/vscode-copy-filename#4]
1. have a random text file opened without a workplace
2. right click on its tab, click "Copy name to clipboard"
3. get a "Copy filename: You must have a workspace opened." error, and no filename in a buffer.

I'm not even sure what a workplace is (I use vscode as an npp linux replacement for simple edits).

A similar extension nemesv.copy-file-name can copy a name without a workplace.

**Comment by Jack89ita** [comment]
Hello @Sco768, thank you for the feedback!
I've removed the mandatory workspace and now this issue should be fixed, just download the latest version of the plugin.
Feel free to reopen this if you encounter again the problem!

**Comment by Sco768** [comment]
Hi @Jack89ita,
Thanks for the fix, there's no error anymore,
however the name is still not copied to the clipboard.
So, steps 1 and 2, then Ctrl + V will paste whatever was in the clipboard previously.
Produced in Ubuntu 18.04 LTS with Unity and vscode 1.33.1

I can't reopen the issue, I can open a new one if you like.
